### ISSUE TITLE
Latest 0.5.4 version - VS2019 doesn't start 

### ISSUE THREAD

**Issue by alfonso73** [Cycling74/min-devkit#158]
Hi, in the latest version (0.5.4) in the "Compile Code" tab on package help none of the bang buttons does lunch VS2019 on Win10 64bit. 
thanks
a.

**Comment by ishipiekie** [comment]
I had the same problem. The /script directory is missing in the min-dev package you get with the package manager. If you add it manually by pulling it from the master, it'll probably work. 

greets, ishi

**Comment by robtherich** [comment]
should be fixed with https://github.com/Cycling74/min-devkit/commit/2b1175903340451d8e7c0edde331e6d7fb63f362

**Comment by omarcostahamido** [comment]
Not fixed! please reopen this issue. 
I think my new issue (#170 ) could be related to this.
